# Generated by Django 2.1.2 on 2019-01-26 02:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0003_auto_20190126_1005'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='created_at',
        ),
    ]
