# Generated by Django 2.1.2 on 2019-01-26 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0004_remove_bloguser_created_at'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bloguser',
            old_name='matric_card',
            new_name='matric_no',
        ),
    ]
