# Generated by Django 2.1.2 on 2019-01-29 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0005_auto_20190126_1017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='user',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='first_name',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='last_name',
            field=models.CharField(max_length=70, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='password',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='bloguser',
            name='username',
            field=models.CharField(default='user', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='matric_no',
            field=models.CharField(default='U1234567A', max_length=9, unique=True),
        ),
    ]
