# Generated by Django 2.1.2 on 2019-01-29 05:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0006_auto_20190129_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloguser',
            name='username',
            field=models.CharField(default='', max_length=20, unique=True),
        ),
    ]
