# Generated by Django 2.1.2 on 2019-01-29 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blogs', '0009_auto_20190129_1346'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bloguser',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='password',
        ),
        migrations.RemoveField(
            model_name='bloguser',
            name='username',
        ),
        migrations.AddField(
            model_name='bloguser',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bloguser',
            name='liked_posts',
            field=models.ManyToManyField(to='blogs.Post'),
        ),
    ]
