# Generated by Django 2.1.2 on 2019-01-29 13:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0011_auto_20190129_2041'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloguser',
            options={'ordering': ('user__last_name',)},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ('post_title',)},
        ),
    ]
